# Generated by Django 5.1 on 2024-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
